# Generated by Django 2.0.3 on 2018-04-01 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='service',
            table='services',
        ),
    ]
